archibaldQuotes = [
    "WHY HELLO COLLECTORS!",
    "Don't forget to spend those Library Points!",
    "Having fun isn't hard when one has a Library Card.",
    "Have you found our books yet?",
    "Tinana is a godsend! How she flawlessly navigates through this maze of shelves I'll never know.",
    "Failure to present proper identification could result in activating lethal anti infiltration automagic protocols!",
    "Only books can take you to places you never thought you'd be!  Oh, and teleportation.  That will do it, too.",
    "Spelljammer in the sky, I can go twice as high.  Take a look, it's in a book, go Collect now!" ,
    "Silence in the library, please",
    "It's all fun and bones until someone misplaces a tome.",
    "Don't forget: The Dewey Decimal System is your friend.",
    "Another misplaced book?! This must be Gertrude's shoddy work...",
    "Adventuring can sound like fun, but the REAL real treasure are the books one finds along the way.",
    "Oh, and don't bring back any, uh... i think it was called, 'Manga'?  The last Collector who did that got his card revoked. That swill has no place in an esteemed library.",
    "So many books, so much time.",
    "Books are full of ideas - perhaps the most powerful of all weapons.  But you should also probably keep your blades sharp, as well.",
    "Magic is not an exact science.  If it were, it would be science.",
    "It's Li-BRARY!  Not Li-Berry!  Get it right!",
    "The Archive requires a book about vampyrism; is there any chance you have encountered The Tome of Strahd?",
    "Collectors come and go, but books are an Archivist's best friend.",
    "GO :clap: GET :clap: MORE :clap: BOOKS! :clap:",
    ":book: :skull: :books:"
]
